### ISSUE TITLE
How do I config the 'platformio.ini'...

### ISSUE THREAD

**Issue by GodayMax** [khoih-prog/WiFiWebServer_RTL8720#4]
I try to config platformio.ini like this, but shows some error like "Error: Could not find the package with 'amebad' requirements for your system 'darwin_x86_64'"

[env:myenv]
platform = amebad
framework =
lib_deps =
     # RECOMMENDED
     # Accept new functionality in a backwards compatible manner and patches
     khoih.prog/WiFiWebServer_RTL8720 @ ^1.0.1

**Comment by khoih-prog** [comment]
Check [**WiFiWebServer_RTL8720 Platformio** #3](https://github.com/khoih-prog/WiFiWebServer_RTL8720/issues/3)

> PIO is currently not supporting [**AmebaD** platform](https://github.com/ambiot/ambd_arduino) as you can see [**PIO Development Platforms**](https://docs.platformio.org/en/latest/platforms/index.html#platforms).
> I suggest that you
> 
> 1. Use **Arduino IDE** which is much easier and powerful enough to use for complex projects.
> 2. Post an `enhancement request` on [**PIO Issue**](https://github.com/platformio/platformio-core/issues) and/or request for help in  [**PIO Forum**](https://community.platformio.org/)
>
