### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by evgarik** [khoih-prog/WiFiWebServer_RTL8720#5]
![Screenshot_12](https://user-images.githubusercontent.com/17249074/142371708-8046e6fd-dc69-4dbf-a224-5f0e676fde66.png)

**Comment by khoih-prog** [comment]
Be sure to check [**Prerequisites**](https://github.com/khoih-prog/WiFiWebServer_RTL8720#prerequisites) and install the required [**functional-vlpp** Library](https://github.com/khoih-prog/functional-vlpp) before complaining.

Working in programming, especially **embedded** field, requires some more diligence and research skills to go further in the career / hobby.
